export const TAGS = {
  genre: [
    { id: 'POP', label: '팝' },
    { id: 'JAZZ', label: '재즈' },
    { id: 'HIPHOP', label: '힙합' },
    { id: 'ELECTRONIC', label: '일렉트로닉' },
    { id: 'CLASSICAL', label: '클래식' },
    { id: 'BALLAD', label: '발라드' },
    { id: 'DANCE', label: '댄스' },
    { id: 'INDIE', label: '인디' },
    { id: 'JPOP', label: '제이팝' },
  ],
  mood: [
    { id: 'DREAMY', label: '몽환적인' },
    { id: 'SAD', label: '우울한' },
    { id: 'WARM', label: '따뜻한' },
    { id: 'URBAN', label: '도시적인' },
    { id: 'ENERGETIC', label: '에너지넘치는' },
    { id: 'ROMANTIC', label: '낭만적인' },
    { id: 'SIMPLE', label: '심플한' },
    { id: 'MODERN', label: '모던한' },
    { id: 'SENSITIVE', label: '감성적인' },
    { id: 'VINTAGE', label: '빈티지한' },
    { id: 'SENSUAL', label: '감각적인' },
    { id: 'LYRICAL', label: '서정적인' },
    { id: 'GROOVY', label: '그루비한' },
    { id: 'MYSTERIOUS', label: '신비로운' },
    { id: 'RICH', label: '풍부한' },
    { id: 'REFRESHING', label: '청량한' },
  ],
};
