export const TAGS = {
  genre: [
    { id: 0, label: '팝' },
    { id: 1, label: '재즈' },
    { id: 2, label: '힙합' },
    { id: 3, label: '일렉트로닉' },
    { id: 4, label: '클래식' },
    { id: 5, label: '발라드' },
    { id: 6, label: '댄스' },
    { id: 7, label: '인디' },
    { id: 8, label: '제이팝' },
  ],
  mood: [
    { id: 0, label: '몽환적인' },
    { id: 1, label: '우울한' },
    { id: 2, label: '따뜻한' },
    { id: 3, label: '도시적인' },
    { id: 4, label: '에너지넘치는' },
    { id: 5, label: '낭만적인' },
    { id: 6, label: '심플한' },
    { id: 7, label: '모던한' },
    { id: 8, label: '감성적인' },
    { id: 9, label: '빈티지한' },
    { id: 10, label: '감각적인' },
    { id: 11, label: '서정적인' },
    { id: 12, label: '그루비한' },
    { id: 13, label: '신비로운' },
    { id: 14, label: '풍부한' },
    { id: 15, label: '청량한' },
  ],
};
