# ddsp_api:latest 이미지를 베이스 이미지로 사용
FROM ddsp_api:latest

# 작업 디렉토리 설정 (코드가 포함된 경로)
WORKDIR /tf/app

# 현재 프로젝트의 모든 파일을 컨테이너에 복사 (Docker 빌드 컨텍스트 내에 있어야 합니다)
COPY . /tf/app

# entrypoint.sh 스크립트를 컨테이너에 복사하고 실행 권한 부여
COPY entrypoint.sh /tf/app/entrypoint.sh
RUN chmod +x /tf/app/entrypoint.sh

# 컨테이너 시작 시 entrypoint.sh 스크립트 실행
CMD ["/tf/app/entrypoint.sh"]
