import Header from '@/components/layout/Header';
import type { Metadata } from 'next';
import React from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased flex justify-center bg-gray-800`}>
        <Header />
        <div className='relative top-15 w-[500px] h-[calc(100dvh-60px)] bg-gray-800 font-[Pretendard]'>
          {children}
        </div>
      </body>
    </html>
  );
}
